version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-

      - run:
          name: install dependencies
          command: |
            pipenv install

      - save_cache:
          paths:
            - ~/.local
            - ~/.cache
          key: cache-{{ checksum "Pipfile.lock" }}

      # run tests!
      - run:
          name: syntax tests
          command: |
            pipenv run python -m compileall main.py cogs custom_classes -fq

      - store_artifacts:
          path: test-reports
          destination: test-reports
